version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        depends_on: 
            - backend
            - client
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '80:80'
    backend:
        build: 
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes: 
            - /app/node_modules
            - ./backend:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPORT=5432
    client:
        stdin_open: true
        tty: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        
