version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    backend:
        build: 
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes: 
            - /app/node_modules
            - ./server:/app
            